---
title: "Dashboard-Visualizations"
author: "Arnab Dey"
date: "3/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Gloal stuff

```{r load packages, message=FALSE}
library(tidyverse)
library(janitor)
library(wordcloud)
library(tm)
library(RColorBrewer)
library(SnowballC)
library(rgdal)
```

# Wordcloud
## Create Dataframe

### Load data as corpus
```{r}
text = df_measures$title
docs = Corpus(VectorSource(text)) 
#inspect(docs)
```

### Text transportation
```{r}
toSpace <- content_transformer(function (x , pattern ) gsub(pattern, "", x))
docs1 = tm_map(docs, toSpace, "-")
docs1 = tm_map(docs1, toSpace, "\\(")
docs1 = tm_map(docs1, toSpace, "\\)")
docs1 = tm_map(docs1, toSpace, ":")
docs1 = tm_map(docs1, toSpace, "|")
docs1 = tm_map(docs1, toSpace, "/")
inspect(docs1)
```

## Clean text
```{r}
# Remove numbers
docs2 <- tm_map(docs1, removeNumbers)
# Remove english common stopwords
docs2 <- tm_map(docs2, removeWords, stopwords("english"))
# Remove your own stop word
docs2 <- tm_map(docs2, removeWords, c("and", "AND")) 
# Remove punctuations
docs2 <- tm_map(docs2, removePunctuation)
inspect(docs2)
```


```{r}
dtm <- TermDocumentMatrix(docs2)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 10)
```


## Plot - Wordcloud - All
```{r}
set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 1,
          max.words=150, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))

```



# Bargraph

## Bargraph for all measures

## Create dataframe
```{r create dataframe}

Dimensions <- c("Psychological \nEmpowerment",
                "Social \nEmpowerment",
                "Education",
                "Legal",
                "Political",
                "Household / \nIntrafamilial \nRelations",
                "Environment and \nSustainability",
                "Time Poverty",
                "Gender \nBased \nViolence",
                "Women's \nEconomic \nEmpowerment",
                "Health",
                "Maternal and \nChild Health",
                "SRH and \nFP",
                "All Measures")

num_measures <- unlist(df_measures %>% select(starts_with("dim")) %>% map(~sum(!is.na(.)))) 
num_measures <- c(num_measures, nrow(df_measures))
df_bar_all <- as.tibble(cbind(Dimensions, num_measures))

df_bar_all <- df_bar_all %>% 
  mutate(num_measures = as.numeric(num_measures))
```

## Plot - Bargraph for all measures
```{r}
plot_bar_all <- ggplot(df_bar_all, aes(fct_reorder(Dimensions, num_measures) , num_measures)) + 
  geom_bar(stat = "identity", width = 0.9, fill = "#157067") + 
  geom_text(aes(label = num_measures), size = 3, vjust = -0.5, color = "black") +
  xlab("Dimensions") + 
  ylab("Number of measures on EMERGE") + 
  theme_minimal()
  
plot_bar_all

```


# Chloropleth

## Create table with count of measures by country 
```{r}

# Create a list of countries in the database as strings
country_list <- df_measures %>% 
  select(countries_spdf) %>% 
  filter(!is.na(countries_spdf))

# Create a dataframe with individual countries
df_countries <- as.data.frame(unlist(strsplit(country_list$countries_spdf, ",")))
colnames(df_countries) <- "countries"


## Match a few remaining countries 
df_countries$countries <- str_replace_all(df_countries$countries, 
                                          "Micronesia", 
                                          "Micronesia, Federated States of")
df_countries$countries <- str_replace_all(df_countries$countries, 
                                          "North Korea", 
                                          "Korea, Democratic People's Republic of")
df_countries$countries <- str_replace_all(df_countries$countries, 
                                          "South Korea", 
                                          "Korea, Republic of")


# Create a dataframe of countries with number of measures in each country
df_countries_n <- df_countries %>% count(countries)
colnames(df_countries_n) <- c("NAME", "num_measures")

# write.csv(df_countries_n, "countries_qualtrics.csv")

```

## Load the geoJason file

```{r}
# Read this shape file with the rgdal library. 
world_spdf <- readOGR( 
  dsn= paste0(getwd(),"/geoDATA/world_shape_file") , 
  layer="TM_WORLD_BORDERS_SIMPL-0.3",
  verbose = FALSE)

# spdf_countries <- as.data.frame(world_spdf@data$NAME)
# write.csv(spdf_countries, "spdf_countries.csv")
```


## Merge the shape file with the Country_measure file

```{r}
world_spdf@data <- world_spdf@data %>% 
  left_join(df_countries_n, by = "NAME") %>% 
  mutate(num_measures = ifelse(is.na(num_measures), 0, num_measures))

# View(world_spdf@data)
```


## Plot the chloropleth

```{r}
# Create a color palette with handmade bins.
mybins <- c(0,10,20,50,100,500)
mypalette <- colorBin( palette="YlOrBr", domain=world_spdf@data$num_measures, na.color="transparent", bins=mybins)
 
# Prepare the text for tooltips:
mytext <- paste(
    "Country: ", world_spdf@data$NAME,"<br/>", 
    "Number of measures: ", world_spdf@data$num_measures, 
    sep="") %>%
  lapply(htmltools::HTML)
 
# Final Map
leaflet(world_spdf) %>% 
  addTiles(options = providerTileOptions(minZoom = 1, maxZoom = 3))  %>% 
  setView(lat=10, lng=0 , zoom=2) %>%
  addPolygons( 
    fillColor = ~mypalette(num_measures), 
    stroke=TRUE, 
    fillOpacity = 0.9, 
    color="white", 
    weight=0.3,
    label = mytext,
    labelOptions = labelOptions( 
      style = list("font-weight" = "normal", padding = "3px 8px"), 
      textsize = "13px", 
      direction = "auto"
    )
  ) %>%
  addLegend( pal=mypalette, values=~num_measures, opacity=0.9, title = "Number of measures", 
             position = "bottomleft" )
  
# save the widget in a html file if needed.
# library(htmlwidgets)
# saveWidget(m, file=paste0( getwd(), "/HtmlWidget/choroplethLeaflet5.html"))
```

